# Generated by Django 2.2.16 on 2022-02-04 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Xidmetin adını daxil edin', max_length=100, verbose_name='Xidmet adı')),
                ('is_active', models.BooleanField(default=True, help_text='Xidmetin aktiv olmasını seçin', verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlər',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Alt xidmetin adını daxil edin', max_length=100, verbose_name='Alt xidmet adı')),
                ('is_active', models.BooleanField(default=True, help_text='Xidmetin aktiv olmasını seçin', verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='core.Service', verbose_name='Xidmət')),
            ],
            options={
                'verbose_name': 'Alt Xidmət',
                'verbose_name_plural': 'Alt Xidmətlər',
                'ordering': ['created_at'],
            },
        ),
    ]
